import React from "react";
import { ProfContextProvider } from "./ProfContext";
import CheckActive from "./components/CheckActive";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className="pt-5 h-full   ">
      <ProfContextProvider>
        <CheckActive />
      </ProfContextProvider>
      {/* <CheckActive /> */}
    </div>
  );
}
